sudo: false
language: node_js
node_js:
  - '8'
  - '9'
install:
  - npm i npminstall && npminstall
before_script:
  - sleep 15
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mongodb
